### ISSUE TITLE
Support Postgres 10 sequences

### ISSUE THREAD

**Issue by kljensen** [subzerocloud/apgdiff#11]
[fordfrog/apgdiff](https://github.com/fordfrog/apgdiff) does not support Postgres 10 sequences. Running apgdiff where there are Postgres 10 sequences will produce an exception similar to the following: `cz.startnet.utils.pgdiff.parsers.ParserException: Cannot parse string: CREATE SEQUENCE`. This is [issue #225](https://github.com/fordfrog/apgdiff/issues/225) on fordfrog/apgdiff and [pull request #228](https://github.com/fordfrog/apgdiff/pull/228) has a fix, but is waiting to be merged. 

It would be useful to me if the subzero apgdiff fork had that fix.

(Thanks for all your help!)

**Comment by ruslantalpa** [comment]
i'll look into this in the near future

**Comment by photz** [comment]
I just got the same error and am investigating.  It seems that by now fordfrog/apgdiff has been updated:
https://github.com/fordfrog/apgdiff/blob/develop/src/main/java/cz/startnet/utils/pgdiff/parsers/CreateSequenceParser.java#L48
It would be great if we could update the version of apgdiff used in the subzero cli.

**Comment by kljensen** [comment]
@photz I used a path to my own apgdiff. I think I built that from source...this was about six months ago. Grepping for AGPDIFF in the subzerocloud tools where show where you can point those tools to your own agpdiff. Good luck!

**Comment by ruslantalpa** [comment]
just built the new version of apgdiff and included it in subzero-cli (currently building, should be up soon v0.1.27)
